/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Chatapp.*;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Queue;
import javax.swing.*;

/**
 *
 * @author eslam
 */
public class UserForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    public UserForm() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        DefaultListModel dlm=new DefaultListModel();
        App.loadContacts();
        if(App.loggedUser.getContacts() !=null ){
        for (int i = 0; i <App.loggedUser.getContacts().size() ; i++) {
            dlm.addElement(""+App.loggedUser.getContacts().get(i).getF_name());
        }
        for (int i = 0; i <App.loadGroup().size() ; i++) {
            dlm.addElement(App.loadGroup().get(i).getName());
        }

    }



        jLabel1.setFont(new java.awt.Font("Arabic Typesetting", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText(App.loggedUser.getF_name().toString());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 40, 176, 32);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/button2.jpg"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(610, 380, 50, 40);

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("User Profile");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(390, 35, 120, 30);

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Story");
        jButton7.setMaximumSize(new java.awt.Dimension(111, 25));
        jButton7.setMinimumSize(new java.awt.Dimension(111, 25));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);

        jButton7.setBounds(530, 35, 120, 30);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Group");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton1ComponentShown(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 440, 120, 32);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Contact");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 440, 120, 32);

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton8.setText("Delete message");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(370, 440, 150, 32);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Log Out");
        jButton3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButton3ComponentShown(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(565, 440, 100, 32);
        jButton3.getAccessibleContext().setAccessibleName("log_out");




        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Contacts");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(250, 35, 120, 30);




        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(153, 153, 153));

        jList1.setBackground(new java.awt.Color(102, 102, 102));
        jList1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 0, 0));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });


        jList1.setModel(dlm);


        jList1.setFixedCellHeight(30);
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 210, 330);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 380, 360, 40);

        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(153, 153, 153));

        jList2.setBackground(new java.awt.Color(102, 102, 102));
        jList2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jList2.setForeground(new java.awt.Color(0, 0, 0));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Empty Chatroom,Send Your first message!" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(230, 100, 440, 270);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 80, 70);

        getContentPane().add(jLabel4);
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setBounds(230, 80, 500, 16);
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Seen:");


        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 690, 500);



        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        ContactDescribtion contact = new ContactDescribtion();
        contact.show();
        dispose();
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        setSize(695, 530);
        jList1.setBackground(new Color(102, 102, 102));
        jList2.setBackground(new Color(102, 102, 102));
        jButton4.setBackground(new Color(102, 102, 102));
        jScrollPane1.setBackground(new Color(102, 102, 102));
        jScrollPane2.setBackground(new Color(102, 102, 102));
        //user image
        ImageIcon img = new ImageIcon(App.loggedUser.getProf_pic());
        Image image = img.getImage();
        Image modifiedImage = image.getScaledInstance(80, 70, java.awt.Image.SCALE_SMOOTH);
        img = new ImageIcon(modifiedImage);
        jLabel3.setIcon(img);
    }//GEN-LAST:event_formComponentShown
    User current_Contact;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AddgroupForm group = new AddgroupForm();
        ImageIcon img = new ImageIcon("D:\\Work\\chatapp\\chat-icon.jpg");
        group.setIconImage(img.getImage());
        group.setTitle("i-chat");
        group.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    //check if it's group[
    boolean isgroup=false;
    int group_id=-1;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultListModel dlm=new DefaultListModel();


        System.out.println("message clicke");;
        //sends the message
        Chatroom cr=new Chatroom();
        Message msg=new Message(5,App.loggedUser,jTextField1.getText(),"23","23",1,"asdfasdf");
       if (!isgroup) {cr=new Chatroom(App.load1to1Chatroom(current_Contact.getId()));
           cr.loadMessages();
           App.sendMessage(cr, msg, App.loggedUser);

       }
        else{
            cr=new Chatroom(group_id);
            cr.loadMessages();
            App.sendMessage(cr,msg,App.loggedUser);

        }

        //refreshes the messages page

        cr.loadMessages();
//        System.out.println(cr.messages.get(1));
//        DefaultListModel dlm=new DefaultListModel();
        ArrayList<Message> messages=cr.messages;
        ArrayList<Integer> msg_ids=new ArrayList<>();
        for (int i = 0; i < messages.size() ; i++) {
          //  System.out.println(messages.get(i).getText());
            msg_ids.add(messages.get(i).getId());
            String messages_string;

            if((messages.get(i).getSender().getId() != App.loggedUser.getId()))
                messages_string="<"+App.getContactName(messages.get(i).getSender().getId())+"> "+messages.get(i).getText();
            else{  messages_string="< Me > "+messages.get(i).getText(); }

            dlm.addElement(messages_string);
        }

        jList2.setModel(dlm);




    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        LoginForm log = new LoginForm();
        ImageIcon img = new ImageIcon("D:\\Work\\chatapp\\chat-icon.jpg");
        log.setIconImage(img.getImage());
        log.setTitle("i-chat");
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed




    ArrayList<Integer> msg_ids = new ArrayList<>();
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("current msgs: "+msg_ids);
        Message deleted_message=new Message(msg_ids.get(jList2.getSelectedIndex()));

        App.deleteMessage(deleted_message);
        msg_ids.remove(msg_ids.get(jList2.getSelectedIndex()));
        DefaultListModel dlm=new DefaultListModel();


        System.out.println("message clicke");;
        //sends the message
        Chatroom cr=new Chatroom();

        if (!isgroup) {cr=new Chatroom(App.load1to1Chatroom(current_Contact.getId()));
            cr.loadMessages();


        }
        else{
            cr=new Chatroom(group_id);
            cr.loadMessages();

        }

        //refreshes the messages page

        cr.loadMessages();
//        System.out.println(cr.messages.get(1));
//        DefaultListModel dlm=new DefaultListModel();
        ArrayList<Message> messages=cr.messages;
//        ArrayList<Integer> msg_ids=new ArrayList<>();
        for (int i = 0; i < messages.size() ; i++) {
            //  System.out.println(messages.get(i).getText());
            msg_ids.add(messages.get(i).getId());
            String messages_string;

            if((messages.get(i).getSender().getId() != App.loggedUser.getId()))
                messages_string="<"+App.getContactName(messages.get(i).getSender().getId())+"> "+messages.get(i).getText();
            else{  messages_string="< Me > "+messages.get(i).getText(); }

            dlm.addElement(messages_string);
        }

        jList2.setModel(dlm);

    }

        private void jList1MouseClicked(java.awt.event.MouseEvent evt) {
    isgroup=false;
        ArrayList<Chatroom> chatrooms=App.loadGroup();
//            ArrayList<Integer> msg_ids = new ArrayList<>();
msg_ids.clear();


           DefaultListModel dlm = new DefaultListModel();
//         //   System.out.println(user);


           //checks if selected value is a group or not
            for (int i = 0; i <chatrooms.size() ; i++) {
                if (jList1.getSelectedValue().equals(chatrooms.get(i).getName())) {
                    isgroup = true;
                    group_id=chatrooms.get(i).getId();
                    break;
                }

            }

            if (!isgroup) {
                User user= App.userGetter(jList1.getSelectedValue(),App.loggedUser);
                current_Contact=user;
                Chatroom cr = new Chatroom(App.load1to1Chatroom(user.getId()));
                cr.loadMessages();
                // System.out.println(cr.messages.get(1));
                jLabel4.setText("Last Seen: " +Chatroom.setLast_seen(App.load1to1Chatroom(user.getId())) +" " + App.getTime());
                ArrayList<Message> messages = cr.messages;
//                ArrayList<Integer> msg_ids = new ArrayList<>();
                for (int i = 0; i < messages.size(); i++) {
                    //    System.out.println(messages.get(i).getText());
                    msg_ids.add(messages.get(i).getId());
                    String messages_string;

                    if ((messages.get(i).getSender().getId() != App.loggedUser.getId()))
                        messages_string = "<" + App.getContactName(messages.get(i).getSender().getId()) + "> " + messages.get(i).getText();
                    else {
                        messages_string = "< Me > " + messages.get(i).getText();
                    }

                    dlm.addElement(messages_string);


                }

                System.out.println(msg_ids);
            }
            else {
                for (int i = 0; i <chatrooms.size(); i++) {
                    if (chatrooms.get(i).getId()==group_id){
                        chatrooms.get(i).loadMessages();
                        ArrayList<Message> messages = chatrooms.get(i).messages;
                        jLabel4.setText("Last Seen: " +Chatroom.setLast_seen(App.load1to1Chatroom(group_id)) +" " + App.getTime());
                        for (int j = 0; j < messages.size(); j++) {

                            msg_ids.add(messages.get(j).getId());
                            String messages_string;

                            if ((messages.get(j).getSender().getId() != App.loggedUser.getId()))
                                messages_string = "<" + App.getContactName(messages.get(j).getSender().getId()) + "> " + messages.get(j).getText();
                            else {
                                messages_string = "< Me > " + messages.get(j).getText();
//                                System.out.println(messages.get(j).getText());
                            }

                            dlm.addElement(messages_string);



                    }
                }

            }

            
        } jList2.setModel(dlm);
    }

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("hellloooooooo");
//            System.out.println(jList2.getSelectedValue());
        System.out.println(msg_ids.get(jList2.getSelectedIndex()));


    }


    private void jButton1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton1ComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ComponentShown

    private void jButton3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton3ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ComponentShown

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        AddContactForm addUser = new AddContactForm();
        ImageIcon img = new ImageIcon("D:\\Work\\chatapp\\chat-icon.jpg");
        addUser.setIconImage(img.getImage());
        addUser.setTitle("i-chat");
        addUser.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Story story = new Story();
        ImageIcon img = new ImageIcon("D:\\Work\\chatapp\\chat-icon.jpg");
        story.setIconImage(img.getImage());
        story.setTitle("i-chat");
        story.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        UserProfile User = new UserProfile();
        ImageIcon img = new ImageIcon("D:\\Work\\chatapp\\chat-icon.jpg");
        User.setIconImage(img.getImage());
        User.setTitle("i-chat");
        User.show();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;

    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
